trigger:
    - master

variables:
    - group: keez-fe-test

stages:
    - stage: Build
      displayName: Build stage

      jobs:
          - job: build_arm_template
            displayName: Build the ARM Template
            pool:
                vmImage: 'windows-latest'
            variables:
                - group: keez-fe-test
            steps:
                - task: CopyFiles@2
                  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)\arm-template'
                  inputs:
                      SourceFolder: deployments
                      Contents: '**\*.json'
                      TargetFolder: '$(Build.ArtifactStagingDirectory)\arm-template'
                - task: Npm@1
                  displayName: 'Install JSON Lint'
                  inputs:
                      command: custom
                      customCommand: 'install jsonlint -g'
                - script: 'jsonlint $(Build.ArtifactStagingDirectory)/arm-template/azuredeploy.json'
                  displayName: 'Validate ARM Template JSON Schema'

                - task: AzureResourceGroupDeployment@2
                  displayName: 'Validate ARM Template Deployment'
                  inputs:
                      azureSubscription: 'test-keez-online-website'
                      resourceGroupName: 'test-keez-website'
                      location: 'West Europe'
                      csmFile: '$(Build.ArtifactStagingDirectory)/arm-template/azuredeploy.json'
                      csmParametersFile: '$(Build.ArtifactStagingDirectory)/arm-template/azuredeploy.test.parameters.json'
                      deploymentMode: 'Validation'

                - task: PublishPipelineArtifact@1
                  displayName: 'Publish Pipeline Artifact'
                  inputs:
                      targetPath: '$(Build.ArtifactStagingDirectory)\arm-template'
                      artifact: 'arm-template'

          - job: Build
            displayName: Build
            pool:
                vmImage: 'ubuntu-latest'
            steps:
                - task: NodeTool@0
                  displayName: 'Install Node.js'
                  inputs:
                      versionSpec: '10.x'

                - script: |
                      npm install -g @angular/cli
                      npm install
                      ng build --prod
                  displayName: 'Build Angular Project'

                - task: CopyFiles@2
                  displayName: 'Copy to artifact staging'
                  inputs:
                      SourceFolder: 'dist/keez-web-app'
                      Contents: '**'
                      TargetFolder: '$(Build.ArtifactStagingDirectory)/Website'

                - publish: '$(Build.ArtifactStagingDirectory)/Website'
                  displayName: 'Publish pipeline artifact'
                  artifact: Website

    - stage: Deploy
      displayName: Deploy stage
      dependsOn: Build
      condition: succeeded()

      jobs:
          - deployment: deploy_arm_templates_incremental
            displayName: 'Deploy ARM Templates Incremental'
            environment: 'Keez-Website-Test'
            pool:
                name: 'Azure Pipelines'
                vmImage: 'windows-2019'
            variables:
                - group: keez-be-test
            strategy:
                runOnce:
                    deploy:
                        steps:
                            - task: DownloadPipelineArtifact@0
                              displayName: 'Download Artifact: arm-template'
                              inputs:
                                  artifactName: 'arm-template'
                                  targetPath: $(System.DefaultWorkingDirectory)/arm-template

                            - task: AzureResourceGroupDeployment@2
                              displayName: 'ARM template deployment'
                              inputs:
                                  azureSubscription: 'test-keez-online-website'
                                  resourceGroupName: 'test-keez-website'
                                  location: 'West Europe'
                                  csmFile: '$(System.DefaultWorkingDirectory)/arm-template/azuredeploy.json'
                                  csmParametersFile: '$(System.DefaultWorkingDirectory)/arm-template/azuredeploy.test.parameters.json'
                                  deploymentMode: Incremental

          - deployment: deploy_system
            displayName: 'Deploy binaries to Azure'
            environment: 'Keez-Website-Test'
            dependsOn:
                - deploy_arm_templates_incremental
            pool:
                vmImage: 'windows-latest'
            strategy:
                runOnce:
                    deploy:
                        steps:
                            - task: AzureFileCopy@3
                              displayName: 'AzureBlob File Copy'
                              inputs:
                                  SourcePath: '$(Pipeline.Workspace)/Website'
                                  azureSubscription: 'test-keez-online-website'
                                  Destination: AzureBlob
                                  storage: 'testkeezwebappstorage'
                                  ContainerName: '$web'

                            - task: AzureCLI@1
                              displayName: 'Purge CDN'
                              inputs:
                                  azureSubscription: 'test-keez-online-website'
                                  scriptLocation: inlineScript
                                  inlineScript: 'az cdn endpoint purge --resource-group "test-keez-website" --name "test-keez-webcdn-endpoint" --profile-name "test-keez-webcdn" --content-paths "/*"'

          - deployment: deploy_arm_templates_complete
            displayName: 'Deploy ARM Templates Complete'
            environment: 'Keez-Website-Test'
            dependsOn:
                - deploy_system
            pool:
                name: 'Azure Pipelines'
                vmImage: 'windows-2019'
            variables:
                - group: keez-be-test
            strategy:
                runOnce:
                    deploy:
                        steps:
                            - task: DownloadPipelineArtifact@0
                              displayName: 'Download Artifact: arm-template'
                              inputs:
                                  artifactName: 'arm-template'
                                  targetPath: $(System.DefaultWorkingDirectory)/arm-template

                            - task: AzureResourceGroupDeployment@2
                              displayName: 'ARM template deployment'
                              inputs:
                                  azureSubscription: 'test-keez-online-website'
                                  resourceGroupName: 'test-keez-website'
                                  location: 'West Europe'
                                  csmFile: '$(System.DefaultWorkingDirectory)/arm-template/azuredeploy.json'
                                  csmParametersFile: '$(System.DefaultWorkingDirectory)/arm-template/azuredeploy.test.parameters.json'
                                  deploymentMode: Complete
